version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - datab
    environment:
      DATABASE_URL: mysql+pymysql://my_user:my_password@datab/lab2python
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  datab:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'lab2python'
      MYSQL_USER: 'my_user'
      MYSQL_PASSWORD: 'my_password'
      MYSQL_ROOT_PASSWORD: 'admin'

